# Permalinks
permalink:        pretty
relative_permalinks: true

# Excerpt
excerpt_separator:  <!--excerpt-end-->

# Setup
title:            Julian Grosshauser
tagline:          Software Engineer
url:              https://juliangrosshauser.com
paginate:         5
baseurl:          /
author:
  name:           Julian Grosshauser
  url:            https://juliangrosshauser.com
  email:          julian@juliangrosshauser.com
