# Permalinks
permalink:            pretty
relative_permalinks:  true

# Excerpt
excerpt_separator:    <!--excerpt-end-->

# Conversion
highlighter:          rouge

# Setup
title:                Julian Grosshauser
url:                  https://juliangrosshauser.com
paginate:             5
baseurl:              /
author:
  name:               Julian Grosshauser
  url:                https://juliangrosshauser.com
  email:              julian@juliangrosshauser.com
  twitter:            jgrosshauser
  github:             github.com/juliangrosshauser
